version: "3"

services:
    app-postgres:
        image: postgres:12.2
        environment:
            - POSTGRES_DB=qapp
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    sudoku:
        build: apps/sudoku
        volumes:
            - ./apps/sudoku:/app
        ports:
            - 4120:4000
        depends_on:
            - app-postgres
        environment:
            NODE_ENV: development
            DB_HOST: app-postgres
            DB_DATABASE: sudoku
            DB_USER: postgres
            DB_PASSWORD: postgres
        command: ["npm", "run", "server-dev"]

    frontend:
        build:
            context: apps/frontend
            dockerfile: dev.Dockerfile
        environment:
            NODE_ENV: development
            VUE_APP_SUDOKU_GRAPHQL_HTTP: http://localhost:4040/graphql
        volumes:
            - ./apps/frontend/src:/app/src
        ports:
            - 8080:8080
